# Private/Whitelisted Server Configuration
# Maximum security for private communities
# Focus: Strict protection with zero tolerance

# General Settings
plugin:
  enabled: true
  debug: false
  update_check: true

# Bot Protection - Maximum security
bot_protection:
  enabled: true
  max_joins_per_ip_per_second: 1      # Very strict
  max_joins_per_ip_per_10_seconds: 2  # Minimal connections
  auto_ban_duration: 900              # 15 minute bans
  
  suspicious_username_patterns:
    - "^[a-z]{1,3}[0-9]{3,8}$"
    - "^[qwertyuiopasdfghjklzxcvbnm]{4,12}$"
    - "^(test|bot|hack|ddos|spam|fake|player)[0-9]*$"
    - "^user[0-9]{1,4}$"
    - "^[A-Za-z]{1,2}[0-9]{4,8}[A-Za-z]{1,2}$"
    
  whitelist_usernames:
    - "ServerOwner"
    - "AdminUser"
    - "HeadModerator"

# VPN Detection - Strict blocking
vpn_detection:
  enabled: true
  api_provider: "ip-api"
  timeout: 3000                       # Shorter timeout
  action: "kick"                      # Immediate kick
  message: "&cVPN/Proxy connections are strictly prohibited on this server!"
  
  whitelist_ips:
    - "127.0.0.1"
    - "192.168.0.0/16"
    - "10.0.0.0/8"

# Challenge Mode - Low threshold for maximum security
challenge_mode:
  enabled: true
  trigger_threshold: 5                # Very sensitive
  duration: 300                       # 5 minutes
  verification_timeout: 30            # Only 30 seconds
  limbo_world: "verification"
  
  welcome_message: |
    &c&lSECURITY VERIFICATION REQUIRED
    &7Verify immediately or be kicked:
    &a/verify {CODE}
    &7Code: &b{CODE} &7(30 seconds)
    
  kick_message: "&cSecurity verification failed. Contact administration."

# Rate Limiting - Very strict
rate_limiting:
  enabled: true
  max_packets_per_second: 50          # Low packet limit
  max_connections_per_ip: 2           # Maximum 2 connections per IP
  connection_throttle: 2000           # 2 second delay between connections

# Logging - Detailed for security monitoring
logging:
  console: true
  file: true
  file_path: "plugins/ShadowDefenderMC/logs/security.log"
  max_file_size: 10485760             # 10MB
  log_level: "DEBUG"                  # Full debug logging

# Messages
messages:
  prefix: "&4[&c🔒 SECURITY&4] "
  bot_kick: "&4SECURITY BREACH: Connection terminated"
  rate_limit_kick: "&4RATE LIMIT: Connection denied"
  vpn_kick: "&4VPN DETECTED: Access denied"
  verification_success: "&a🔓 Security clearance granted"
  verification_failed: "&4❌ SECURITY VIOLATION: Invalid code"
  challenge_activated: "&4🚨 SECURITY ALERT: Server under protection"

# Advanced Settings - Maximum security
advanced:
  use_async_processing: true
  cache_duration: 300                 # 5 minutes only
  cleanup_interval: 60                # Standard cleanup
  max_cached_ips: 5000               # Smaller cache
  thread_pool_size: 2                # Fewer threads (smaller server)